export const jobNames = [
  'VP of Misc. Stuff',
  'Genius',
  'Director of First Impressions',
  'Sous Chef',
  'The Resinator',
  'Arts and Crafts Designer',
  'Director, Ethical Hacking',
  'Master of Disaster',
  'Project Meanie',
  'Crayon Evangelist',
  'Catalyst',
  'Director of First Impressions',
  'Creator of Opportunities',
  'Ambassador of Buzz',
  'Digital Prophet',
  'Chief Curator',
  'Head of Global Trends and Futuring',
  'Chief Cheerleader',
  'Chief Amazement Officer',
  'President and TeaEO',
  'Chief Troublemaker',
];
